version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: . ./venv/bin/activate
      - run: pip3 install -r requirements.txt
      - run: python3 -m pytest